version: 0.0
os: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# giving permission to files and folders to centos user in home directory
files:
  - source: /
    destination: /home/ubuntu/webapp

hooks:
  ApplicationStop:
    - location: ./codeDeploy/applicationStop.sh
      timeout: 300
    
  BeforeInstall:
    - location: ./codeDeploy/beforeInstall.sh
      timeout: 300
      
  AfterInstall:
    - location: ./codeDeploy/afterInstall.sh
      timeout: 300

  ApplicationStart:
    - location: ./codeDeploy/applicationStart.sh
      timeout: 300